### ISSUE TITLE
Can I relicense my own Fair License project into Apache 2.0?

### ISSUE THREAD

**Issue by jpventura** [fairsource/fairsource#5]
I am creating a project and, in order to have some copyright protection to avoid a cannibalized competition, I would like to release the project under Fair License.

Initially I thought about providing a Affero GPL v3.0 dual-license and, once the project is completed (i.e. release 1.0.0), I would relicense the project under Apache 2.0.

However I am considering using Fair License instead of AGPL v3.0 due its simplicity.

Since I am the sole copyright owner, I would like to know if/how I could change the license, also granting the Apache License to clients that already possess older versions of the project as well.

**Comment by Aspie96** [comment]
(**I am not a lawyer and this is not legal advice**)

A license is a permission from the copyright holder.

If you are the only copyright holder (which also implies you didn't get any contributions from others) then you do not need a license at all and the terms and conditions of the licenses you give to others don't apply to you at all.

You may use your own works however you want, you don't need your own permission.

As an analogy: if you allow me to use your car, provided that I meet certain conditions (only wearing clean shoes), does it mean that you have any less of a right to ride your car? Of course not. You don't need any permission at all.

The idea of copyright is that there are things only the copyright holder can do. "No license" = "no permission" and it is maximally restrictive. A license is a permission, to someone else, to do things that are otherwise forbidden to them by copyrgith law.

**Comment by Aspie96** [comment]
Note: DO NOT call this the "Fair License". The Fair License is here: http://opensource.org/licenses/fair.php

This is Fair Use License

**Comment by unional** [comment]
> This is Fair Use License

Fair Use License or Fair Source License?

**Comment by chadwhitacre** [comment]
Closing in light of https://github.com/fairsource/fairsource/pull/9. 🙏
